name: 'deploy'

on:
  workflow_run:
    workflows: [codeqc]
    branches: [master]
    types: [completed]

jobs:
  deploy:
    name: 'BuildDeployStaging'
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_push_flags: --force
          git_remote_url: 'ssh://dokku@158.101.144.203:22/flexi-license'
          ssh_private_key: ${{ secrets.JP2_PRIVATE_KEY }}
