name: 'Routine'

on: [push, pull_request]

jobs:
  codeqc:
    name: 'CodeQualityCheck'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Using Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: 'Install dependencies'
        run: npm install
      - name: 'Formatting check'
        run: npm run format:check
      - name: 'Lint'
        run: npm run lint
      - name: 'Type Checking'
        run: npm run type-check
      - name: 'Unit Test'
        run: npm run test
  deploy:
    name: 'BuildDeployStaging'
    needs: 'codeqc'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_push_flags: --force
          git_remote_url: 'ssh://dokku@158.101.144.203:22/flexi-license'
          ssh_private_key: ${{ secrets.JP2_PRIVATE_KEY }}
